---
version: "3"
services:

  603web:
    image: nginx:latest
    container_name: digital603
    restart: unless-stopped
    ports:
      - "192.168.1.239:5001:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.primaryweb.rule=Host(`www.digital603.com`)"
      - "traefik.http.routers.primaryweb.entrypoints=websecure"
      - "traefik.port=5001"

networks:
  proxy:
    external: true
