---
version: "3"
services:

  digital603-build:
    container_name: www-digital-603-builder
    image: nhjay/digital-603:latest
    build: .

  digital-603:
    container_name: www-digital-603
    image: nhjay/digital-603:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8084:80"
    labels:
      - traefik.enable=true
      - traefik.network=proxy
      - traefik.http.routers.digital-603.rule=Host(`www.digital603.com`)
      - traefik.http.routers.digital-603.entrypoints=websecure
      - traefik.http.services.digital-603.loadbalancer.server.port=8084
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./public:/var/www/html

networks:
  proxy:
    external: true
